config/routes.rb
Rails.application.routes.draw do
  resources :limit_ip_paths, path: 'admin'
  
  namespace 'monitor' do
    get '/', action: :index

    namespace :api do
      get :index
    end
  end
  
  get 'proxy/show'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ip_history.rb
class IpHistory < ApplicationRecord
end

app/models/limit_ip_path.rb
class LimitIpPath < ApplicationRecord
end

app/models/proxy_control.rb
class ProxyControl < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/concerns/response.rb
module Response
  def json_response(object, status = :ok)
    render json: formatted_response(object), status: status
  end

  def formatted_response(object)
    {
      header: {
        page: object.current_page,
        limit_value: object.limit_value,
        total_pages: object.total_pages,
        total_count: object.total_count,
      },
      data: object
    }
  end
end

app/controllers/limit_ip_paths_controller.rb
class LimitIpPathsController < ApplicationController
  before_action :set_limit_ip_path, only: %i[ show edit update destroy ]

  # GET /limit_ip_paths or /limit_ip_paths.json
  def index
    @limit_ip_paths = LimitIpPath.all
  end

  # GET /limit_ip_paths/1 or /limit_ip_paths/1.json
  def show
  end

  # GET /limit_ip_paths/new
  def new
    @limit_ip_path = LimitIpPath.new
  end

  # GET /limit_ip_paths/1/edit
  def edit
  end

  # POST /limit_ip_paths or /limit_ip_paths.json
  def create
    @limit_ip_path = LimitIpPath.new(limit_ip_path_params)

    respond_to do |format|
      if @limit_ip_path.save
        format.html { redirect_to @limit_ip_path, notice: "Limit ip path was successfully created." }
        format.json { render :show, status: :created, location: @limit_ip_path }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @limit_ip_path.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /limit_ip_paths/1 or /limit_ip_paths/1.json
  def update
    respond_to do |format|
      if @limit_ip_path.update(limit_ip_path_params)
        format.html { redirect_to @limit_ip_path, notice: "Limit ip path was successfully updated." }
        format.json { render :show, status: :ok, location: @limit_ip_path }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @limit_ip_path.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /limit_ip_paths/1 or /limit_ip_paths/1.json
  def destroy
    @limit_ip_path.destroy
    respond_to do |format|
      format.html { redirect_to limit_ip_paths_url, notice: "Limit ip path was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_limit_ip_path
      @limit_ip_path = LimitIpPath.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def limit_ip_path_params
      params.require(:limit_ip_path).permit(:ip, :path, :max_requests_hour, :max_requests_day)
    end
end

app/controllers/monitor/api_controller.rb
class Monitor::ApiController < ApplicationController
  include Response

  DEFAULT_PAGE = 1
  DEFAULT_LIMIT_VALUE = 25
  DEFAULT_START_DATE = '1990-01-01'
  DEFAULT_END_DATE = Time.now

  def index
    response = ActiveModel::SerializableResource.new(requests).to_json
    json_response(requests)
  end

  private

  def requests
    conditions = {}
    conditions[:created_at] = start_at..end_at
    conditions[:ip] = params[:ip] unless params[:ip].nil?
    conditions[:path] = params[:path] unless params[:path].nil?

    IpHistory.where(conditions)
      .page(page)
      .per(limit_value)
  end

  def page
    params[:page].nil? ? DEFAULT_PAGE : params[:page].to_i
  end

  def limit_value
    params[:limit_value].nil? ? DEFAULT_LIMIT_VALUE : params[:limit_value].to_i
  end

  def start_at
    params[:start_at].nil? ? DEFAULT_START_DATE : params[:start_at]
  end

  def end_at
    params[:end_at].nil? ? DEFAULT_END_DATE : params[:end_at]
  end
end

app/controllers/monitor_controller.rb
class MonitorController < ApplicationController
  def index
  end
end

app/controllers/proxy_controller.rb
class ProxyController < ApplicationController
  def show
    render json: { error: request.env['ERROR_INFO'] }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/limit_ip_paths_helper.rb
module LimitIpPathsHelper
end

app/helpers/monitor/api_helper.rb
module Monitor::ApiHelper
end

app/helpers/monitor_helper.rb
module MonitorHelper

  def path_request_rank
    @path_request_rank ||= IpHistory.group('path').order('count(path) DESC').limit(10).select('path').count
  end
end

app/helpers/proxy_helper.rb
module ProxyHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MeliProxy</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/limit_ip_paths/_form.html.erb
<%= form_with(model: limit_ip_path) do |form| %>
  <% if limit_ip_path.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(limit_ip_path.errors.count, "error") %> prohibited this limit_ip_path from being saved:</h2>

      <ul>
        <% limit_ip_path.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :ip %>
    <%= form.text_field :ip, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :path %>
    <%= form.text_field :path, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :max_requests_hour %>
    <%= form.number_field :max_requests_hour, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :max_requests_day %>
    <%= form.number_field :max_requests_day, class: 'form-control' %>
  </div>

  <div class="actions mt-4">
    <%= form.submit 'Create new rule', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/limit_ip_paths/edit.html.erb
<h1>Editing Limit Ip Path</h1>

<%= render 'form', limit_ip_path: @limit_ip_path %>

<%= link_to 'Show', @limit_ip_path %> |
<%= link_to 'Back', limit_ip_paths_path %>

app/views/limit_ip_paths/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <p id="notice"><%= notice %></p>

      <h1>Custom request rules</h1>

      <table class="table">
        <thead>
          <tr>
            <th>Ip</th>
            <th>Path</th>
            <th>Max requests hour</th>
            <th>Max requests day</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @limit_ip_paths.each do |limit_ip_path| %>
            <tr>
              <td><%= limit_ip_path.ip %></td>
              <td><%= limit_ip_path.path %></td>
              <td><%= limit_ip_path.max_requests_hour %></td>
              <td><%= limit_ip_path.max_requests_day %></td>
              <td><%= link_to 'Show', limit_ip_path %></td>
              <td><%= link_to 'Edit', edit_limit_ip_path_path(limit_ip_path) %></td>
              <td><%= link_to 'Destroy', limit_ip_path, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <br>

      <%= link_to 'Create new rule', new_limit_ip_path_path, class: 'btn btn-primary' %>
    </div>
  </div>
</div>

app/views/limit_ip_paths/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1>Creating a new rule</h1>

      <%= render 'form', limit_ip_path: @limit_ip_path %>

      <%= link_to 'Back', limit_ip_paths_path %>
    </div>
  </div>
</div>

app/views/limit_ip_paths/show.html.erb
<div class="container">
  <div class="row mt-2">
    <div class="col-md-12">
      <% if notice.present? %>
        <div class="alert alert-info" role="alert">
          <%= notice %>
        </div>
      <% end %>

      <h2>Looking at an existing rule</h2>

      <p>
        <strong>Ip:</strong>
        <%= @limit_ip_path.ip %>
      </p>

      <p>
        <strong>Path:</strong>
        <%= @limit_ip_path.path %>
      </p>

      <p>
        <strong>Max requests hour:</strong>
        <%= @limit_ip_path.max_requests_hour %>
      </p>

      <p>
        <strong>Max requests day:</strong>
        <%= @limit_ip_path.max_requests_day %>
      </p>

      <%= link_to 'Edit', edit_limit_ip_path_path(@limit_ip_path) %> |
      <%= link_to 'Back', limit_ip_paths_path %>
    </div>
  </div>
</div>

app/views/monitor/api/index.html.erb
<h1>Monitor::Api#index</h1>
<p>Find me in app/views/monitor/api/index.html.erb</p>

app/views/monitor/index.html.erb
<div class="container-flex monitor">

  <div class="row">
    <div class="col-md-12 text-center p-2 bg-dark">
      <h1 style="color: white;">Monitoring Panel</h1>
    </div>
  </div>

  <div class="row text-center m-4">
    <div class="col-md-1"></div>
    <div class="col-md-10">
      <h2 class="fw-light">Requests in the last 24 hours</h2>
      <%= line_chart IpHistory.group_by_hour(:created_at, last: 24).count %>
    </div>
  </div>

  <div class="row text-center m-4">
    <hr/>
    <div class="col-md-1"></div>
    <div class="col-md-10">
      <h2 class="fw-light">Requests in the last 7 days</h2>
      <%= line_chart IpHistory.group_by_day(:created_at, last: 7).count %>
    </div>
  </div>

  <div class="row text-center m-4">
    <hr/>
    <div class="col-md-1"></div>
    <div class="col-md-10">
      <h2 class="fw-light">Requests in the last 4 weeks</h2>
      <%= line_chart IpHistory.group_by_week(:created_at, last: 8).count  %>
    </div>
  </div>

  <div class="row text-center m-4">
    <hr/>
    <div class="col-md-1"></div>
    <div class="col-md-10">
      <h2 class="fw-light">Most used paths (Everytime)</h2>
      <table class="table table-striped">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Path</th>
            <th scope="col">Requests</th>
          </tr>
        </thead>
        <tbody>
          <% path_request_rank.each_with_index do |path, index| %>
            <tr>
              <th scope="row"><%= index + 1 %></th>
              <td><%= path[0] %></td>
              <td><%= path[1] %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/proxy/show.html.erb
<h1>Proxy#show</h1>
<p>Find me in app/views/proxy/show.html.erb</p>